### ISSUE TITLE
Code=dumped, Signal=TRAP

### ISSUE THREAD

**Issue by ikswokor** [MusicPlayerDaemon/mpdscribble#13]
Hi,

i cant run mpdscribble and idk why. This is error message. Last time when i correctly scrobble track is before mpd update (ver 0.21.3 (2018/11/16))

![2019-03-09-17:23:02](https://user-images.githubusercontent.com/5803407/54074227-46ad5800-4290-11e9-954d-22e03886aefa.png)

**Comment by MaxKellermann** [comment]
Need a backtrace.
