### ISSUE TITLE
Very short songs are not scrobbled

### ISSUE THREAD

**Issue by billop** [MusicPlayerDaemon/mpdscribble#23]
I've noticed that two songs I have which are both 12 seconds long never get scrobbled. The currently playing thing works, but they don't actually get scrobbled.

**Comment by toofar** [comment]
I don't think last fm accepts scrobbles for short songs (less than 30s) https://www.last.fm/api/scrobbling#when-is-a-scrobble-a-scrobble

**Comment by MaxKellermann** [comment]
True, that's a last.fm limitation. Thanks for pointing out.
