### ISSUE TITLE
last.fm scrobbler changed API

### ISSUE THREAD

**Issue by arbitrary-dev** [MusicPlayerDaemon/mpdscribble#27]
http://post.audioscrobbler.com/

>Audioscrobbler submissions system.
>http://www.audioscrobbler.net/

And `url = http://www.audioscrobbler.net/` results in:
>[last.fm] handshake error: got HTTP status 301

**Comment by BeyondMagic** [comment]
http://post.audioscrobbler.com/ still working.

**Comment by tomchiverton** [comment]
Same here. Getting now playing fine on last.fm with the default

```
[last.fm]
url = http://post.audioscrobbler.com/
```

Not a bug, close ?
