### ISSUE TITLE
Confusing Error Message

### ISSUE THREAD

**Issue by worldpe** [MusicPlayerDaemon/mpdscribble#32]
I am trying to run the command
`mpdscribble --conf="/home/wpeace/.config/mpdscribble/mpdscribble.conf" --daemon-user="wpeace"`

but get the error message 
`Section has neither 'file' nor 'url'`

When I did 
`mpdscribble --conf="~/.config/mpdscribble/mpdscribble.conf" --daemon-user="wpeace"`
I was told
`Failed to open ~/.config/mpdscribble/mpdscribble.conf: No such file or directory`, which I didn't expect either.

I got the program off the AUR and there was no default config, but I copied one I dug around in the github repo to find, my config file is:

>[mpdscribble]
>pidfile = /var/run/mpdscribble.pid
>log = ~/.config/mpdscribble/mpdscribble.log
>verbose = 2
>journal_interval = 600
>
>port = 6600
>
>[last.fm]
>url = https://post.audioscrobbler.com/
>username = WhoDidYouKnow
>password = 1e067f691be7b1f7e9502ba79d272514
>journal = ~/.config/mpdscribble/lastfm.journal
>
>[libre.fm]
>url = http://turtle.libre.fm/
>username = WhereAreWeSeeing
>password = 70b8122aeaa5ef53ae37148fbaf37e4f
>journal = /var/cache/mpdscribble/librefm.journal
>
>[file]
>file = /var/log/mpdscribble/log`

Some of the config comes from this guide: `https://ubuntu-mate.community/t/how-to-install-and-setup-mpd-mpdscribble-ncmpcpp/8439`, I can't see anything obvious being refernecing, I have both a file and url value, and there wasn't a [url] section listed in the default config, so I don't think that needs to be added anywhere. However i Have a [file] section and file variable, so I am not sure why it appears to be missing.

**Comment by ammgws** [comment]
What happens if you remove the "[mpdscribble]" from the start of the file?

My config doesn't have that, those options are all just listed at the top level.

I think what is happening is that it is being interpreted as a scrobble backend, and there is no url or file under [mpdscribble] hence the error.

**Comment by dhruvSHA256** [comment]
correct syntax to specify config file is
```mpdscribble --conf /home/wpeace/.config/mpdscribble/mpdscribble.conf --daemon-user wpeace```

**Comment by ammgws** [comment]
@MaxKellermann I believe this can be closed now
