### ISSUE TITLE
Update config.guess / config.sub

### ISSUE THREAD

**Issue by Holzhaus** [MusicPlayerDaemon/mpdscribble#4]
For the next released version I propose to update `config.guess` and `config.sub` in the `build` directory to their latest versions.

I'm unable to build mpdscribble on `aarch64`, because the version used for mpdscribble 0.22 is quite old (December 2009) and does not support this architecture yet.
If i manually pull the latest versions of these files from http://git.savannah.gnu.org/cgit/config.git/tree/ everything works fine.

**Comment by MaxKellermann** [comment]
These files get updated every time a source tarball is made. They are not present in git. To update all autotools files in your build directory, just call `./autogen.sh`
Closing this issue, because what you request is already done automatically.
