### ISSUE TITLE
Support scrobbling partway through the track instead of only at the end.

### ISSUE THREAD

**Issue by jaccarmac** [MusicPlayerDaemon/mpdscribble#5]
Most other scrobblers allow setting a percentage of a track to scrobble at from 51-100%, a set time to scrobble at no matter what (like 4:00), rules to scrobble long tracks multiple times, or a combination of all three. These would be nice features to have for mpdscribble.

**Comment by MunifTanjim** [comment]
I think it's already there: https://github.com/MusicPlayerDaemon/mpdscribble/blob/048bc62e43a6000f99291522b725f1ddd48864c1/src/Main.cxx#L44-L55

**Comment by jaccarmac** [comment]
Indeed, and while that particular code is new the function is not. Wonder why I'm only seeing scrobbles happen at track completion?

**Comment by MunifTanjim** [comment]
Probably one of the two reasons:
- The song is not submitted halfway through the duration. It's submitted only after a new song is started (either it has played it's whole duration or you changed the song after playing more than half of it).
- You're using an old build.

**Comment by MaxKellermann** [comment]
Closing, because this is already implemented.
And yes, mpdscribble only scrobbles at track completion, i.e. when the track playback ends.
