### ISSUE TITLE
Does mpdscribble support the Last.fm 2.0 API?

### ISSUE THREAD

**Issue by garaud** [MusicPlayerDaemon/mpdscribble#9]
Hi,
I have used mpdscribble for several years. I scrobble to Last.fm.

Last.fm changes the version of their API which is not backward compatible. See:

* [Blog post about the change](https://getsatisfaction.com/lastfm/topics/closure-of-legacy-last-fm-site-pages)
* [Scrobbling 2.0 Documentation](https://www.last.fm/api/scrobbling)

I just updated my `/etc/mpdscibble.conf` file with the new URL http://ws.audioscrobbler.com/2.0/ and I have HTTP 400 Bad Request error. Maybe I miss something.

Moreover, it's not clear to me how can I debug this. I don't how I can find the HTTP request send to the Last.fm API. I'll take a look to the source code.

Thanks,
Damien

**Comment by garaud** [comment]
I drop mpdscribble to another program which is compatible with the last.fm API.

I use https://github.com/hawx/mpd-scrobbler/

Let's reopen the issue if someone want to implement this in mpdscribble.

**Comment by MaxKellermann** [comment]
Oh, yet another scrobbler! I wish people would improve existing projects instead of starting new ones from scratch.
